### ISSUE TITLE
想问下大佬这个l的参数是干嘛用的?

### ISSUE THREAD

**Issue by xhay125** [792301982/Xiudong-Script#11]
![image](https://user-images.githubusercontent.com/32445465/148666942-8f251e2a-d239-49cf-95df-173246565903.png)

**Comment by yangn0** [comment]
当时网站前端 做的js加密

**Comment by ludobb** [comment]
> 当时网站前端 做的js加密

请问一下大佬这个加密是你破解了秀动的 还是你作为post请求头做的防止反爬的加密呢

**Comment by yangn0** [comment]
> > 当时网站前端 做的js加密
> 
> 请问一下大佬这个加密是你破解了秀动的 还是你作为post请求头做的防止反爬的加密呢

主要是做js逆向。当时秀动js里写的，网页上ajax表单提交的时候，会增加这一条加密项。

**Comment by ludobb** [comment]
> 

谢谢大佬超快速的回复hhh 刚接触这一块 还不太了解 请问这个 l 是自己通过network里的参数自行构建的意思嘛 还是随意构造的呢?这个的目的主要还是加密以防网站方反爬机制逮到嘛?

> > > 当时网站前端 做的js加密
> > 
> > 
> > 请问一下大佬这个加密是你破解了秀动的 还是你作为post请求头做的防止反爬的加密呢
> 
> 主要是做js逆向。当时秀动js里写的，网页上ajax表单提交的时候，会增加这一条加密项。

**Comment by yangn0** [comment]
> > 
> 
> 谢谢大佬超快速的回复hhh 刚接触这一块 还不太了解 请问这个 l 是自己通过network里的参数自行构建的意思嘛 还是随意构造的呢?这个的目的主要还是加密以防网站方反爬机制逮到嘛?
> 
> > > > 当时网站前端 做的js加密
> > > 
> > > 
> > > 请问一下大佬这个加密是你破解了秀动的 还是你作为post请求头做的防止反爬的加密呢
> > 
> > 主要是做js逆向。当时秀动js里写的，网页上ajax表单提交的时候，会增加这一条加密项。
> 
> 

秀动那边的程序员在js里自己手写的l的值。他这样做 其实 实质是用时间戳来做反爬。参数l 只是用来给时间戳 加盐

**Comment by ludobb** [comment]
> > > 
> > 
> > 
> > 谢谢大佬超快速的回复hhh 刚接触这一块 还不太了解 请问这个 l 是自己通过network里的参数自行构建的意思嘛 还是随意构造的呢?这个的目的主要还是加密以防网站方反爬机制逮到嘛?
> > > > > 当时网站前端 做的js加密
> > > > 
> > > > 
> > > > 请问一下大佬这个加密是你破解了秀动的 还是你作为post请求头做的防止反爬的加密呢
> > > 
> > > 
> > > 主要是做js逆向。当时秀动js里写的，网页上ajax表单提交的时候，会增加这一条加密项。
> 
> 秀动那边的程序员在js里自己手写的l的值。他这样做 其实 实质是用时间戳来做反爬。参数l 只是用来给时间戳 加盐

了解了了解了 感谢大佬的解答!
